# Generated by Django 6.0.5 on 2026-06-07 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('writing_type', models.CharField(choices=[('sher', 'Sher'), ('ghazal', 'Ghazal'), ('nazm', 'Nazm'), ('shayari', 'Shayari'), ('quote', 'Quote')], default='sher', max_length=20)),
                ('language', models.CharField(choices=[('urdu', 'Urdu'), ('hindi', 'Hindi'), ('english', 'English')], default='urdu', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
