# Generated by Django 6.0.5 on 2026-05-28 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Poet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('biography', models.TextField()),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='poets/')),
            ],
        ),
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('writing_type', models.CharField(choices=[('sher', 'Sher'), ('ghazal', 'Ghazal'), ('nazm', 'Nazm'), ('shayari', 'Shayari'), ('quote', 'Quote')], max_length=20)),
                ('language', models.CharField(choices=[('urdu', 'Urdu'), ('hindi', 'Hindi'), ('english', 'English')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(to='poetry.category')),
                ('poet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writings', to='poetry.poet')),
            ],
        ),
    ]
