# Generated by Django 6.0.5 on 2026-05-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
