# Generated by Django 6.0.5 on 2026-05-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0002_writing_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poet_name', models.CharField(max_length=255)),
                ('poet_biography', models.TextField(blank=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('writing_type', models.CharField(choices=[('sher', 'Sher'), ('ghazal', 'Ghazal'), ('nazm', 'Nazm'), ('shayari', 'Shayari'), ('quote', 'Quote')], max_length=20)),
                ('language', models.CharField(choices=[('urdu', 'Urdu'), ('hindi', 'Hindi'), ('english', 'English')], max_length=20)),
                ('submitted_by', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
