# Generated by Django 6.0.5 on 2026-05-29 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0003_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('writing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='poetry.writing')),
            ],
            options={
                'unique_together': {('user', 'writing')},
            },
        ),
    ]
